### ISSUE TITLE
Use default value (Y) when pressing enter?

### ISSUE THREAD

**Issue by delphaber** [jmeinerz/rebasing-hook#1]
Nice script! Thank you :)

I think that [here](https://github.com/jmeinerz/rebasing-hook/blob/master/hooks/post-rewrite#L16), when you ask to keep or discard changes, if I press "enter" then it should behave like I pressed Y. That's because, in bash convention, the upper flag is the default one.

What do you think? :)

**Comment by jmeinerz** [comment]
Hi @delphaber, thanks for opening this 👍

I totally agree with you. I have made some modifications locally so that it works on any POSIX shell and it also makes the script less verbose. I plan on pushing those later today but I want to test them out for a while first.

As soon as I commit the changes I'll tag this issue so you're notified
